DjangoEcomerce/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView


from django.urls import include, path
# from django.conf.urls import url, include #SERA DESCONTINUADA

from core import views


app_name = 'DjangoEcomerce'
urlpatterns = [
    path('admin/', admin.site.urls),

    #url ira ser substituido por path, url sera depreciada
    # url(r'^$',views.index, name="index"),
    # url(r'^contato/$',views.contact, name="contact"),
    # url(r'^produto/$',views.product, name="product"),
    # url(r'^produtos/', include(('catalog.urls', 'catalog'), namespace='catolog')), #novo modo de usar o include com url
    
    path('',views.IndexView.as_view(), name='index'),
    path('contato/', views.contact, name='contact'),
    
    # path('produtos/', include('catalog.urls'), name='catalog'),
    path('catalogo/', include(('catalog.urls', 'catalog'), namespace='catalog')),
    path('contas/', include(('accounts.urls', 'accounts'), namespace='accounts')),
    # path('catalogo/', include('catalog.urls'), name='catalog'),

    path('entrar',LoginView.as_view(), name='login'),
    path('sair',LogoutView.as_view(), name='logout')
]

accounts/urls.py
from django.urls import path

from . import views

urlpatterns = [
	path('registro/', views.RegisterView.as_view(), name='register'),
]

catalog/urls.py
# from django.conf.urls import url
from django.urls import path


from . import views

urlpatterns = [
	path('',views.ProductListView.as_view(), name='product_list'),
	path('<slug:slug>/', views.CategoryListView.as_view(), name='category'),
	path('produtos/<slug:slug>/', views.product, name='product'),
]

core/models.py
from django.db import models

# Create your models here.

core/forms.py
from django import forms
from django.core.mail import send_mail
from django.conf import settings

class ContactForm(forms.Form):
	name = forms.CharField(label='Nome')
	email = forms.EmailField(label='E-mail')
	message = forms.CharField(label='Mensagem', widget=forms.Textarea(attrs={'rows':'4'}))


	def send_mail(self):
		nome = self.cleaned_data['name']
		email = self.cleaned_data['email']
		message = self.cleaned_data['message']
		message = 'Nome: {} \nEmail: {}\n {}'.format(nome,email,message)
		print('-------------chegou aqui\n')
		#1 parametro = titulo da msg, 2 mensagem, 3 email de saida, 4 lista com emails destino
		send_mail(
			'Contato do Django Ecomerce',message, settings.DEFAULT_FROM_EMAIL, [settings.DEFAULT_FROM_EMAIL]
			)

	# def __init__(self, *args, **kwargs):
	# 	super(ContactForm, self).__init__(*args, **kwargs)
	# 	self.fields['name'].widget.attrs['class'] = 'form-control'
	# 	self.fields['email'].widget.attrs['class'] = 'form-control'
	# 	self.fields['message'].widget.attrs['class'] = 'form-control'

core/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.views.generic import View, TemplateView, CreateView


from .forms import ContactForm


# Create your views here.

class IndexView(TemplateView):
	
	template_name = 'index.html'




def contact(request):

	success = False

	form = ContactForm(request.POST or None)
	if form.is_valid():
		form.send_mail()
		success = True
	
	context = {
		'form' : form,
		'success': success
	}
	return render(request, 'contact.html', context)

def product(request):
	return render(request, 'product.html')

core/templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
	<title>{% block title %}Djando e-comerce{% endblock %}</title>
	
	<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/estilo.css' %}">
	<script type="text/javascript" src="{% static 'js/jquery.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/bootstrap.js' %}"></script>
</head>
<body>
		
	<nav class="navbar navbar-expand-lg navbar-dark bg-dark negrito">
		<div class="container">
			<a class="navbar-brand" href="{% url 'index'%}">Django Ecomerce</a>
			<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
		    	<span class="navbar-toggler-icon"></span>
			</button>
			<div class="collapse navbar-collapse" id="navbarText">
			    <ul class="navbar-nav mr-auto">
			    	<li class="nav-item">
			        	<a class="nav-link" href="{% url 'index'%}">Inicio</a>
			      	</li>
			      	<li class="nav-item dropdown"> 
			      		<a class="nav-link dropdown-toggle" href="{{ get_absolute_url }}" id="navbardrop" data-toggle="dropdown">
				        Categorias
				    	</a>
				    	<div class="dropdown-menu">
				      		{% for cat in categories %}
				        		<a class="dropdown-item" href="{{ cat.get_absolute_url }}">{{ cat }}</a>
				        	{% endfor %}
				      </div>
				    </li>
			      	<li class="nav-item">
			        	<a class="nav-link" href="{% url 'contact'%}">Contato</a>
			      	</li>
			    </ul>

			    	{% if user.is_authenticated %}
				    <a><span class="navbar-text">Olá {{ user.username }} &nbsp &nbsp</span></a>
					
	
				    <li class="dropdown navbar-nav"> 
			      		<a class="nav-link dropdown-toggle" href="{{ get_absolute_url }}" id="dropconta" data-toggle="dropdown">
				        Minha conta
				    	</a>
				    	<div class="dropdown-menu">
				      		
				        	<a class="dropdown-item" href="{% url 'logout' %}">Sair</a> 	
				      </div>
				    </li>
				    {% else %}
				    <a href="{% url 'accounts:register' %}"><span class="navbar-text">Registrar-se &nbsp &nbsp</span></a>
				    <a href="{% url 'login' %}"><span class="navbar-text">Entrar</span></a>
				    {% endif %}
			</div>
		</div>
	</nav>


<div class="container conteudo">
	{% block container %} {% endblock %}
</div>
<footer class="footer">
  <div class="container">
		<div class="row">
			<div class="col-lg-10 col-sm-9 col-md-9">
				<ul class="list-unstyled lista-footer">
					<li><a href="{% url 'index'%}">Inicio</a></li>
					<li><a href="{% url 'catalog:product_list' %}">Produdos</a></li>
					<li><a href="{% url 'contact'%}">Contato</a></li>
					<li><a href="">Termos e Privacidade</a></li>
				</ul>
			</div>
			<div class="col-lg-2 col-sm-3 col-md-3">
				<ul class="list-unstyled lista-footer">
					<li><a href="#top">Voltar ao Topo</a></li>
				</ul>
			</div>
		</div>
	</div>
</footer>
</body>

</html>

core/templates/contact.html
{% extends "base.html" %}

{% load widget_tweaks %}

{% block title %}
	Contato | {{ block.super }}
{% endblock %}

{% block container %}
	<h1 class="font-grande negrito">Fale conosco</h1>
	{% if success %}
	<div class="alert alert-success">
		Mensagem enviada com sucesso
	</div>
	{% endif %}
	<form class="form-horizontal" action="" method="post">
		{% csrf_token %}
		<fieldset>
			{% for field in form %}
				<div class="form-group row {% if field.errors %} has-error {% endif %}">
	    			<label for="{{ field.auto_id }}" class="col-md-3 col-form-label col-form-label-lg direita negrito">{{ field.label }}</label>
	    			<div class="col-md-9">
	      				{% render_field field class='form-control form-control-lg' %}
	    				{% for error in field.errors%}
	    					<span class="help-block"> {{ error }}</span>
	    				{% endfor %}
	    			</div>
	  			</div>			
	  		{% endfor %}

	  		<div class="form-group">
	  			<div class="col-md-12 col-md-offset-3 direita">
	  				<button type="submit" class="btn btn-primary">Enviar</button>
	  			</div>
	  		</div>
		</fieldset>
	</form>

	<!-- comentario no template do django -->
	{% comment %}

	<form>
	  	<div class="form-group row">
	    	<label for="nome" class="col-sm-2 col-form-label col-form-label-lg direita negrito">Nome</label>
	    	<div class="col-sm-10">
	      		<input type="text" class="form-control form-control-lg" id="nome" placeholder="Nome">
	    	</div>
	  	</div>

	  	<div class="form-group row">
	    	<label for="email" class="col-sm-2 col-form-label col-form-label-lg direita negrito">E-mail</label>
	    	<div class="col-sm-10">
	      		<input type="email" class="form-control form-control-lg" id="email" placeholder="E-mail">
	    	</div>
	  	</div>

	  	<div class="form-group row">
	    	<label for="mensagem" class="col-sm-2 col-form-label col-form-label-lg direita negrito">Mensagem</label>
	    	<div class="col-sm-10">
	      		<textarea type="text-area" rows="4" class="form-control form-control-lg" id="mensagem" placeholder="Digite sua mensagem"></textarea>
	    	</div>
	  	</div>

	  	<div class="form-group">
	  		<div class="col-sm-9 col-sm-offset-3">
	  			<button type="submit" class="btn btn-primary">Enviar</button>
	  		</div>
	  	</div>
	</form>

	{% endcomment %}

{% endblock %}

core/templates/index.html
{% extends "base.html" %}

	{% block container %} 
	
	<h1 class="font-grande negrito">Django E-Comerce</h1>

	<p class="font-media">Um texto qualquer</p>

	<button class="btn navbar-dark bg-dark text-branco negrito">Saiba mais</button>

	{% endblock %}

core/templates/pagination.html
	<div class="row">
		<div class="col-md-12">
			<nav>
				<ul class="pagination">
					{% for page in paginator.page_range %}
					<li class="page-item {% if page_obj.number == page %} active {% endif %}">
						<a class="page-link" href="?page={{page}}{{getvars}}">{{page}}</a>
					</li>
					{% endfor %}
				</ul>
			</nav>
		</div>
	</div>



	<!-- comentario abaixo -->

	{% comment %}
	<div class="row">
		<div class="col-md-12">
			<nav>
				<div class="btn-group mr-2" role="group">
				<div class="pagination">
					{% for page in paginator.page_range %}
						
						<a type="button" class="btn btn-success" href="?page={{page}}{{getvars}}">{{page}}</a>
						
					{% endfor %}
				</div>
				</div>
			</nav>
		</div>
	</div>
	{% endcomment %}

core/templates/product.html
{% extends "base.html" %}

{% block title %}
	Produto | {{ block.super }}
{% endblock %}

{% block container %}
	<div class="row margin-sup">
		<div class="col-sm-4">
			<a href="#" class="thumbnail">
				<img src="http://placehold.it/350x250" alt="" />
			</a>
		</div>
		<div class="col-sm-8">
			<dl>
				<dt>Lorem ipsum:</dt>
				<dd>Lorem ipsum dolor sit amet</dd>
				<dt>Lorem ipsum:</dt>
				<dd>Lorem ipsum dolor sit amet</dd>
				<dt>Lorem ipsum:</dt>
				<dd>Lorem ipsum dolor sit amet</dd>
				<dt>Lorem ipsum:</dt>
				<dd>Lorem ipsum dolor sit amet</dd>
			</dl>
		</div>
	</div>
{% endblock %}